import axios from 'axios';
import Head from 'next/head';
import { Video } from '../types';
import VideoItem from '../components/VideoItem';

interface Props {
  videos: Video[];
}

export default function Home({ videos }: Props) {
  return (
    <>
      <Head>
        <title>Tik Tik</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='h-[calc(100vh-90px)] overflow-hidden overflow-y-auto'>
        {videos.map((video) => (
          <VideoItem key={video._id} video={video} />
        ))}
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const { data: videos } = await axios.get('http://localhost:3000/api/post');

  return { props: { videos } };
}
